# Generated by Django 3.2.12 on 2022-11-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster_path', models.CharField(blank=True, max_length=150, null=True)),
                ('movie_id', models.IntegerField()),
                ('overview', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('poster_path', models.CharField(blank=True, max_length=150, null=True)),
                ('overview', models.TextField()),
                ('release_date', models.CharField(max_length=100)),
                ('runtime', models.IntegerField()),
                ('genres', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MovieProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=100)),
                ('logo_path', models.CharField(blank=True, max_length=150, null=True)),
                ('provider_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchMulti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster_path', models.CharField(blank=True, max_length=150, null=True)),
                ('multi_id', models.IntegerField()),
                ('overview', models.TextField()),
                ('media_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('poster_path', models.CharField(blank=True, max_length=200, null=True)),
                ('tv_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TVDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('poster_path', models.CharField(blank=True, max_length=150, null=True)),
                ('overview', models.TextField()),
                ('genres', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TVProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=100)),
                ('logo_path', models.CharField(blank=True, max_length=150, null=True)),
                ('provider_id', models.IntegerField()),
            ],
        ),
    ]
